#!/usr/bin/env bash
# This script transfers a file from the client to the server using SCP

# Check if 4 arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USER=$3
SSH_KEY=$4

# Perform the SCP transfer
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USER"@"$SERVER_IP":~/
