#!/usr/bin/env bash

apt-get update

apt-get install -y nginx

# Make sure Nginx is listening on port 80
ufw allow 'Nginx HTTP'

# Check if Nginx is running
service nginx start

# Add an HTML page containing "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html
