#!/usr/bin/env bash
# Install Nginx and set up the server
apt-get update -y

apt-get install -y nginx

# Make sure Nginx is listening on port 80
ufw allow 'Nginx HTTP'
ufw allow 'Open SSH'

# Check if Nginx is running
service nginx restart

# Add an HTML page containing "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html
